SELECT * FROM OPENQUERY(ADB,
' 
    SELECT 
        TRIM(AROOT.ACCTNUM) as [Account Number],
        CAST(FNAMEVALUE(ACCTBALS.BALANCES, ''TrxLastPmtAmt'') as SQL_NUMERIC(12, 2)) [Total Paid],
        CONCAT(SUBSTRING(CAST(COMMCODE.RATE1 as SQL_CHAR),1,5),''%'') [Fee Rate],
        CAST(COMMCODE.RATE1/100 * CAST(FNAMEVALUE(ACCTBALS.BALANCES, ''TrxLastPmtAmt'') as SQL_NUMERIC(12, 2)) as SQL_NUMERIC(12,2)) [Fee To TMP],
        CONVERT(CLAIM.LASTPMNT, SQL_DATE) [Last Payment Date],
        CAST(FNAMEVALUE(ACCTBALS.BALANCES, ''IDPPRJ'') as SQL_NUMERIC(12, 2)) as [Current Balance],
        CAST(FNAMEVALUE(ACCTBALS.BALANCES, ''IDPPRJ_O'') as SQL_NUMERIC(12, 2)) as [Total Delinquent Amount],
        CLIENTGP.DESCRIPT [Client]
    FROM 
        AROOT
            INNER JOIN CLAIM on CLAIM.PKAROOT = AROOT.PKAROOT 
            INNER JOIN STATCODE on STATCODE.PKSTATCODE = CLAIM.PKSTATCODE
            INNER JOIN CLIENT on CLIENT.PKCLIENT = AROOT.PKCLIENT
            INNER JOIN CLIENTGP on CLIENTGP.PKCLIENTGP = CLIENT.PKCLIENTGP
            INNER JOIN COMMCODE on COMMCODE.PKCOMMCODE = CLIENT.PKCOMMCODE
            LEFT JOIN ACCTBALS on ACCTBALS.FILEID = TRIM(AROOT.ACCTNUM)+''.001''
    WHERE 
        CONVERT(CLAIM.LASTPMNT, SQL_DATE) BETWEEN CONVERT(CURDATE() - DAY(CURDATE() - 1), SQL_DATE) AND CONVERT(CURDATE(), SQL_DATE)
    ORDER BY 
        CONVERT(CLAIM.LASTPMNT, SQL_DATE)
        CLIENTGP.DESCRIPT, 
        TRIM(AROOT.ACCTNUM)
')