SELECT *
FROM OPENQUERY
(ADB,
'
SELECT 
    Acctnum
    , TRIM(FirstName) [FirstName]
    , TRIM(MiddleName) [MiddleName]
    , TRIM(LastName) [LastName]
FROM AROOT
    JOIN ACOMP ON ACOMP.PKAROOT = AROOT.PKAROOT AND TRIM(ACOMP.ENTRYTYPE) = ''DEB''
    JOIN DEMOG ON DEMOG.PKDEMOG = ACOMP.PKENTITY 
    JOIN CLAIM ON CLAIM.PKAROOT = AROOT.PKAROOT 
    JOIN STATCODE ON STATCODE.PKSTATCODE = CLAIM.PKSTATCODE 
WHERE 
    STATCODE.CODE < ''500''
ORDER BY ACCTNUM ASC
')
WHERE
(
    FirstName LIKE '%[0-9]'
    OR
    MiddleName LIKE '%[0-9]'
    OR
    LastName LIKE '%[0-9]'
)