SELECT * FROM OPENQUERY(adb,'
SELECT 
ACCTNUM [Account Number],
ACTCODE.CODE [Action Code],
STATCODE.CODE [Status Code]
FROM AROOT
JOIN AIQ on AIQ.PKAROOT = AROOT.PKAROOT
JOIN ACTCODE on AIQ.PKACTCODE = ACTCODE.PKACTCODE
INNER JOIN CLAIM on CLAIM.PKAROOT = AROOT.PKAROOT 
INNER JOIN STATCODE on STATCODE.PKSTATCODE = CLAIM.PKSTATCODE
WHERE
STATCODE.CODE = ''026''
AND ACTCODE.CODE LIKE ''%LSK%''
')
UNION
SELECT * FROM OPENQUERY(adb,'
SELECT 
ACCTNUM [Account Number],
ACTCODE.CODE [Action Code],
STATCODE.CODE [Status Code]
FROM AROOT
JOIN AIQ on AIQ.PKAROOT = AROOT.PKAROOT
JOIN ACTCODE on AIQ.PKACTCODE = ACTCODE.PKACTCODE
INNER JOIN CLAIM on CLAIM.PKAROOT = AROOT.PKAROOT 
INNER JOIN STATCODE on STATCODE.PKSTATCODE = CLAIM.PKSTATCODE
WHERE
STATCODE.CODE = ''025''
AND ACTCODE.CODE LIKE ''%STP%''
')

ORDER BY [Account Number]